---
server:
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: fauxuser
    password: fauxpassword
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pazrael/squishy-eyeballs-config
          search-paths:
            - 'minis*'
            - 'station*'